# Generated by Django 5.1.1 on 2024-11-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondimentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('tastes', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.UUIDField(null=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.JSONField()),
                ('condiments', models.JSONField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_collection', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('collection_name', models.CharField(default='My Collection', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TastePrefModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.UUIDField(null=True, unique=True)),
                ('sweet_offset', models.FloatField(default=1)),
                ('salty_offset', models.FloatField(default=1)),
                ('sour_offset', models.FloatField(default=1)),
                ('spicy_offset', models.FloatField(default=1)),
                ('health_conditions', models.JSONField(default=[])),
            ],
        ),
    ]
